import '../globals.css'
import { Inter, Roboto_Mono } from 'next/font/google';
import localfont from 'next/font/local'
import Navbar from './components/navbar/Navbar';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



const Neue = localfont({
  src:[
    {
      path: '../../public/fonts/NeueMachina-Light.otf',
      weight:"300",
    },
    {
      path:'../../public/fonts/NeueMachina-Regular.otf',
      weight:"400",
    },
    {
      path:'../../public/fonts/NeueMachina-Ultrabold.otf',
      weight:"800",
    }
  ],
  variable: '--font-neue',
})



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${Neue.variable}`}>
      <body>
      <Navbar/>
        {children}
        
        </body>
    </html>
  )
}
